# Generated by Django 2.2.4 on 2022-06-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0002_auto_20220629_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(to='djangoApp.User'),
        ),
    ]
